
#ifndef ZCL_THERMOSTAT_UI_CFG_H
#define ZCL_THERMOSTAT_UI_CFG_H

/*********************************************************************
 * CONSTANTS
 */

/**
 *  @brief	thermostatu UI configuration cluster Attribute IDs
 */
#define ZCL_THERMOSTAT_UI_CFG_ATTRID_TEMPERATUREDISPLAYMODE         0x0000
#define ZCL_THERMOSTAT_UI_CFG_ATTRID_KEYPADLOCKOUT                  0x0001
#define ZCL_THERMOSTAT_UI_CFG_ATTRID_SCHEDULEPROGRAMMINGVISIBILITY  0x0002

#define ZCL_THERMOSTAT_UI_CFG_ATTRID_OFFSET_TEMP		0x0100
#define ZCL_THERMOSTAT_UI_CFG_ATTRID_OFFSET_HUMI		0x0101
#define ZCL_THERMOSTAT_UI_CFG_ATTRID_COMFORT_MIN_T		0x0102
#define ZCL_THERMOSTAT_UI_CFG_ATTRID_COMFORT_MAX_T		0x0103
#define ZCL_THERMOSTAT_UI_CFG_ATTRID_COMFORT_MIN_H		0x0104
#define ZCL_THERMOSTAT_UI_CFG_ATTRID_COMFORT_MAX_H		0x0105
#define ZCL_THERMOSTAT_UI_CFG_ATTRID_DISPLAY_OFF		0x0106

#define ZCL_THERMOSTAT_UI_CFG_ATTRID_MEASURE_INTERVAL	0x0107

status_t zcl_thermostat_ui_cfg_register(u8 endpoint, u16 manuCode, u8 attrNum, const zclAttrInfo_t attrTbl[], cluster_forAppCb_t cb);

#endif	/* ZCL_THERMOSTAT_UI_CFG_H */
